# -*- coding: utf-8 -*-
"""ENGG2112_Group21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lo6Nk59cBoclchVjBlYdwG2IunQoWEhm
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
from pathlib import Path

FEATURE_COLUMNS = [
    "Area",
    "Soil",
    "hourly_precip_mean",
    "hourly_precip_std",
    "hourly_runoff_mean",
    "hourly_runoff_std",
    "sand",
    "silt",
    "clay",
]


def load_data(csv_path="final_data.csv"):
    csv_path = Path(csv_path)
    if not csv_path.exists():
        csv_path = Path.cwd() / csv_path
    if not csv_path.exists():
        csv_path = Path("/Users/shahranazim/Desktop") / csv_path

    df = pd.read_csv(csv_path)
    df = df.dropna(subset=FEATURE_COLUMNS + ["Real?"])
    df = df.copy()
    df["risk_label"] = np.where(df["Real?"], "High", "Low")
    return df


def prepare_features(df):
    X = df[FEATURE_COLUMNS]
    y = df["risk_label"]
    return X, y


def train_decision_tree(X, y, max_depth=5, random_state=42):
    model = DecisionTreeClassifier(max_depth=max_depth, random_state=random_state)
    model.fit(X, y)
    return model


def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification report:\n", classification_report(y_test, y_pred))


def plot_risk_tree(model, feature_names, class_names):
    plt.figure(figsize=(16, 10))
    plot_tree(
        model,
        feature_names=feature_names,
        class_names=class_names,
        filled=True,
        rounded=True,
        fontsize=10,
    )
    plt.title("Flood Risk Decision Tree")
    plt.tight_layout()
    plt.show()


def generate_risk_map(df, model):
    df_map = df.copy()
    df_map["predicted_risk"] = model.predict(prepare_features(df_map)[0])
    df_map["risk_value"] = df_map["predicted_risk"].map({"Low": 0, "High": 1})

    plt.figure(figsize=(10, 6))
    scatter = plt.scatter(
        df_map["long"],
        df_map["lat"],
        c=df_map["risk_value"],
        cmap="RdYlBu_r",
        alpha=0.75,
        edgecolor="k",
        linewidth=0.4,
    )
    plt.colorbar(scatter, ticks=[0, 1], label="Predicted risk\n(0=Low,1=High)")
    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    plt.title("Flood Risk Mapping by Location")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()


def plot_feature_importance(model, feature_names):
    importance = model.feature_importances_

    plt.figure(figsize=(8, 5))
    plt.bar(feature_names, importance)
    plt.xlabel("Features")
    plt.ylabel("Importance Score")
    plt.title("Feature Importance in Flood Risk Prediction")
    plt.xticks(rotation=15)
    plt.tight_layout()
    plt.show()

    for feature, score in zip(feature_names, importance):
        print(f"{feature}: {score:.3f}")


def main():
    df = load_data("final_data.csv")
    X, y = prepare_features(df)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )
    model = train_decision_tree(X_train, y_train, max_depth=5)

    print("\nModel evaluation on test set:\n")
    evaluate_model(model, X_test, y_test)

    print("\nDecision tree structure:\n")
    plot_risk_tree(model, feature_names=X.columns.tolist(), class_names=model.classes_)

    print("\nGenerating example risk map:\n")
    generate_risk_map(df, model)

    print("\nFeature importance analysis:\n")
    plot_feature_importance(model, X.columns.tolist())

    sample = pd.DataFrame(
        [
            {
                "Area": 120000.0,
                "Soil": 20.0,
                "hourly_precip_mean": 0.0005,
                "hourly_precip_std": 0.0008,
                "hourly_runoff_mean": 0.00012,
                "hourly_runoff_std": 0.00035,
                "sand": 0.40,
                "silt": 0.35,
                "clay": 0.25,
            }
        ]
    )
    sample_X = sample[FEATURE_COLUMNS]
    print("Sample input:\n", sample.to_dict(orient="records"))
    print("Predicted risk:", model.predict(sample_X)[0])

if __name__ == "__main__":
    main()